# Project: Graficas
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = conOpenGL.o
LINKOBJ  = conOpenGL.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -L"C:/Users/IsaiasGL/OneDrive - Instituto Politecnico Nacional/ESFM/3er semestre/Programación 1/Examen/8_Fractales/Graficos/lib" -mwindows -lopengl32 lib/Logo.a lib/Funciones.a lib/Koch.a lib/Rama.a lib/Dragon.a Hil/Hil.a Sierpinski/Spk.a Abelson/C.a Gosper/G.a "Mandelbrot square/M.a" "Abelson polygons/P.a" "Abelson triangles/N.a" "Mandelbrot hooked/H.a" Malmberg/X.a nMalmberg/FM.a
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/IsaiasGL/OneDrive - Instituto Politecnico Nacional/ESFM/3er semestre/Programación 1/Examen/8_Fractales/Graficos/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"C:/Users/IsaiasGL/OneDrive - Instituto Politecnico Nacional/ESFM/3er semestre/Programación 1/Examen/8_Fractales/Graficos/include"
BIN      = Graficas.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

conOpenGL.o: conOpenGL.c
	$(CC) -c conOpenGL.c -o conOpenGL.o $(CFLAGS)
